### PR TITLE
Basic Atlas webhook support

### PR DESCRIPTION
**Pull request by jage**
screen shot 2015-06-11 at 16 28 58

Unfortunately the notifications options in Atlas is limited now. Either we get just critical errors (it will not send webhooks when it gets up again). Or we get everything, everything looks like too much, it will send webhooks even for services that are ok.

### CODE REVIEW

**Comment by jage** [comment]
This is mostly a copy-paste job from the pingdom plugin.

**Comment by walro** [comment]
> Unfortunately the notifications options in Atlas is limited now

Won't the lack of up cause us extra work? At least if it triggers as much as it does in the mac mini's browser

**Comment by jage** [comment]
True. I'm interested to see how many notifications we get, if it's false alarms we can just disable the webhook in Atlas.

**Comment by walro** [comment]
> True. I'm interested to see how many notifications we get, if it's false alarms we can just disable the webhook in Atlas.

Alright

**Comment by jage** [comment]
Another issue is that we can't silence these in a good way (like we've started doing with Nagios).

**Comment by jage** [comment]
So this will probably be a short lived experiment. :(

**Pull request closed without merging**
